# Generated by Django 2.1.5 on 2019-02-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('project_image', models.ImageField(blank=True, upload_to='proImg')),
                ('project_url', models.URLField()),
                ('project_url_name', models.CharField(max_length=50)),
                ('project_source_code', models.URLField(null=True)),
                ('project_date', models.DateTimeField(blank=True, null=True)),
                ('project_category', models.CharField(choices=[('WEB-DEVELOPMENT-DJANGO', 'DJANGO'), ('ANDROID', 'ANDROID')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quote', models.CharField(max_length=100)),
            ],
        ),
    ]
