# Generated by Django 2.1.5 on 2019-01-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_title', models.CharField(max_length=50)),
                ('port_catego', models.CharField(max_length=50)),
                ('port_date', models.DateTimeField(auto_now=True)),
                ('port_image', models.ImageField(upload_to='portImg')),
            ],
        ),
    ]
