# Generated by Django 2.1.5 on 2019-02-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainport', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_category',
            field=models.CharField(choices=[('WEB-DEVELOPMENT-DJANGO', 'DJANGO'), ('ANDROID', 'ANDROID')], default=True, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='project_date',
            field=models.DateTimeField(null=True),
        ),
    ]
