# Generated by Django 2.1.5 on 2019-02-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainport', '0005_auto_20190204_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_category',
            field=models.CharField(choices=[('WEB-DEVELOPMENT-DJANGO', 'DJANGO'), ('ANDROID', 'ANDROID')], max_length=30),
        ),
    ]
