# Generated by Django 2.1.5 on 2019-02-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainport', '0006_auto_20190204_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_source_code',
            field=models.URLField(null=True),
        ),
    ]
