# Generated by Django 2.1.7 on 2019-02-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainport', '0009_auto_20190220_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
