# Generated by Django 2.1.5 on 2019-02-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('coder_message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GetInTouch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='I love hearing things form you')),
            ],
        ),
        migrations.CreateModel(
            name='MessageMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=50)),
                ('your_email', models.EmailField(max_length=254)),
                ('your_subject', models.CharField(max_length=50)),
                ('your_message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GITHUB', models.URLField(blank=True)),
                ('LINKEDIN', models.URLField(blank=True)),
                ('TWITTER', models.URLField(blank=True)),
                ('PINTEREST', models.URLField(blank=True)),
            ],
        ),
    ]
