# Generated by Django 2.1.5 on 2019-01-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=50)),
                ('yout_email', models.EmailField(max_length=254)),
                ('your_subject', models.CharField(max_length=50)),
                ('your_message', models.TextField()),
            ],
        ),
    ]
