# Generated by Django 2.1.5 on 2019-01-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmessageme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('coder_message', models.TextField()),
            ],
        ),
    ]
