# Generated by Django 2.1.5 on 2019-01-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmessageme', '0002_panelmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GITHUB', models.URLField()),
                ('LINKEDIN', models.URLField()),
                ('TWITTER', models.URLField()),
                ('PINTEREST', models.URLField()),
            ],
        ),
        migrations.RenameField(
            model_name='messageme',
            old_name='yout_email',
            new_name='your_email',
        ),
        migrations.RemoveField(
            model_name='panelmodel',
            name='coder_message',
        ),
        migrations.RemoveField(
            model_name='panelmodel',
            name='title',
        ),
        migrations.AddField(
            model_name='panelmodel',
            name='get_panel',
            field=models.TextField(default='get in touch'),
        ),
        migrations.AddField(
            model_name='panelmodel',
            name='panel_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
