# Generated by Django 2.1.5 on 2019-01-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmessageme', '0003_auto_20190126_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panelmodel',
            name='get_panel',
        ),
        migrations.RemoveField(
            model_name='panelmodel',
            name='panel_title',
        ),
        migrations.AddField(
            model_name='panelmodel',
            name='coder_message',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='panelmodel',
            name='title',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
