# Generated by Django 2.1.5 on 2019-01-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmessageme', '0004_auto_20190126_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediamodel',
            name='GITHUB',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='socialmediamodel',
            name='LINKEDIN',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='socialmediamodel',
            name='PINTEREST',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='socialmediamodel',
            name='TWITTER',
            field=models.URLField(blank=True),
        ),
    ]
