# Generated by Django 2.1.5 on 2019-01-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendmessageme', '0005_auto_20190126_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Get_In_Touch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default='I love hearing things form you')),
            ],
        ),
    ]
