# Generated by Django 2.1.5 on 2019-01-26 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendmessageme', '0006_get_in_touch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Get_In_Touch',
            new_name='GetInTouch',
        ),
    ]
