# Generated by Django 2.1.5 on 2019-01-26 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendmessageme', '0007_auto_20190126_2212'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PanelModel',
            new_name='CoderModel',
        ),
    ]
