# Generated by Django 2.1.5 on 2019-02-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HTML5', models.CharField(max_length=50)),
                ('CSS3', models.CharField(max_length=50)),
                ('DJANGO', models.CharField(max_length=50)),
                ('PYTHON', models.CharField(max_length=50)),
                ('ANDROID', models.CharField(max_length=50)),
            ],
        ),
    ]
