# Generated by Django 2.1.5 on 2019-01-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0002_aboutmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
